app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace='todo'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from unicodedata import name
from django.urls import path
from .views import todo_list, todo_create, todo_update, todo_delete, todo_detail

app_name = 'todo'

urlpatterns = [
    path('', todo_list, name ='todo_list'),
    path('todos/<int:pk>/', todo_detail, name='todo_detail'),
    path('todos/create/', todo_create, name = 'todo_create'),
    path('todos/<int:pk>/update/', todo_update, name='todo_update'),
    path('todos/<int:pk>/delete/', todo_delete, name='todo_delete')
]

todo/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
STATUS_CHOICES = [
    ('N', 'Новая'),
    ('P', 'В процессе'),
    ('C', 'Выполнена')
]

class Todo(models.Model):
    description = models.CharField(verbose_name='Описание', max_length=300, null=False, blank=False)
    status = models.CharField(verbose_name='Статус', choices=STATUS_CHOICES, max_length=1, null=False, blank=False, default=STATUS_CHOICES[0][0])
    text = RichTextField(null=True, blank=True)
    date = models.DateField(verbose_name='Дата закрытия', null=True, blank=True)

    def __str__(self):
        return f'{self.description} - {self.status}'
    
    def get_choice(self, choice):
        return [c[0] for c in STATUS_CHOICES if c == choice]

todo/forms.py
from secrets import choice
from telnetlib import STATUS
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['description', 'status', 'date', 'text']
        widgets = {
            'description':forms.TextInput(attrs={'class':'form-control', 'id':'description'}),
            'status':forms.Select(attrs={'class':'form-control select-status', 'id':'text'}),
            'date':forms.TextInput(attrs={'class':'form-control due-date', 'id':'status'}),
        }

todo/views.py
from audioop import reverse
from django.shortcuts import render, redirect, reverse
from todo.services import todo_services
from todo.utils import todo_utils
from .forms import TodoForm

def todo_list(request):
    todo_list = todo_services.get_all_todos()
    context = {
        'todo_list':todo_list,
    }
    return render(request, 'todo/todo_list.html', context)


def todo_create(request):
    form = TodoForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('todo:todo_list')
    
    context = {
        'form': form
    }
    return render(request, 'todo/todo_create.html', context)

def todo_update(request, pk):
    todo = todo_services.get_todo_by_pk(pk)
    form = TodoForm(request.POST or None, instance=todo)
    if form.is_valid():
        form.save()
        return redirect(reverse('todo:todo_detail', kwargs={'pk':todo.pk}))
    context = {
        'todo':todo,
        'form':form,
    }
    return render(request, 'todo/todo_update.html', context)

def todo_delete(request, pk):
    todo = todo_services.get_todo_by_pk(pk)
    if request.method == 'POST':
        todo.delete()
        return redirect('todo:todo_list')
    context = {
        'todo': todo, 
    }
    return render(request, 'todo/todo_delete.html', context)

def todo_detail(request, pk):
    todo = todo_services.get_todo_by_pk(pk)
    context = {
        'todo': todo,
    }
    return render(request, 'todo/todo_detail.html', context)
    
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo list page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'todo/css/style.css' %}">
</head>

<body>
    <div class="container-sm mt-5">
        <header>
            <h1 class="text-center app-title"><a href="{% url 'todo:todo_list' %}">Todo App</a></h1>
            {% block navigation %}
            {% endblock navigation %}
        </header>
        <div class="w-50 p-3 m-auto todos">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</body>

</html>

todo/templates/todo/todo_create.html
{% extends 'base.html' %}
{% block navigation %}
<div class="w-50 p-3 m-auto d-flex justify-content-start">
    <a class="btn btn-secondary" href="{% url 'todo:todo_list' %}">Назад</a>
</div>
{% endblock navigation %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.media}}
    <label for="description" class="form-label">Название задачи</label>
    {{form.description}}
    <label for="text" class="form-label">Описание</label>
    {{form.text}}
    <label for="status" class="form-label">Статус</label>
    {{form.status}}
    <label for="date" class="form-label">Срок выполнения(y-m-d)</label>
    <p> <input type="date" id="date" name="date" class="form-control due-date"></p>
    <button class="btn btn-primary mt-3" type="submit">Создать</button>
</form>
{% endblock content %}

todo/templates/todo/todo_delete.html
{% extends 'base.html' %}
{% block navigation %}
<div class="w-50 p-3 m-auto d-flex justify-content-start">
    <a class="btn btn-secondary" href="{% url 'todo:todo_detail' todo.pk %}">Назад</a>
</div>
{% endblock navigation %}

{% block content %}
<ul class="list-group">
    <li class="list-group-item d-flex">
        <div class="p-2 w-100 todos-item-text">
            <div class="text-muted mb-2" style="font-size:20px;">
                {% if todo.date %}
                {{ todo.date.day }}.{{ todo.date.month }}.{{ todo.date.year }}
                {% else %}
                Нет срока
                {% endif %}
                {% if todo.status == "N" %}
                <span class="badge bg-primary">{{ todo.get_status_display }}</span>
                {% elif todo.status == "C"%}
                <span class="badge bg-secondary">{{ todo.get_status_display }}</span>
                {% else %}
                <span class="badge bg-success">{{ todo.get_status_display }}</span>
                {% endif %}
            </div>
            <p class="fs-5">{{todo.description}}</p>
        </div>
    </li>
    <li class="list-group-item d-flex" style="border-bottom: None;">
        <div class="p-2 w-100 todos-item-text">
            <h5>Вы действительно желаете удалить запись?</h5>
        </div>
    </li>
    <li class="list-group-item d-flex">
        <div class="p-2 w-100 todos-item-text">
            <form action="{% url 'todo:todo_delete' todo.pk %}" method="POST">
                {% csrf_token %}
                <input type="text" name="confirm" hidden>
                <button type="submit" class="btn btn-danger" style="min-width: 100px;">Да</button>
                <a href="{% url 'todo:todo_detail' todo.pk %}" class="btn btn-secondary"
                    style="min-width: 100px;">Нет</a>
            </form>
        </div>
    </li>
</ul>
{% endblock content %}

todo/templates/todo/todo_detail.html
{% extends 'base.html' %}
{% load static %}

{% block navigation %}
<div class="w-50 p-3 m-auto d-flex justify-content-start">
    <a class="btn btn-secondary" href="{% url 'todo:todo_list' %}">Назад</a>
</div>
{% endblock navigation %}

{% block content %}
<ul class="list-group">
    <li class="list-group-item d-flex">
        <div class="p-2 w-100 todos-item-text">
            <div class="text-muted mb-2" style="font-size:20px;">
                {% if todo.date %}
                {{ todo.date.day }}.{{ todo.date.month }}.{{ todo.date.year }}
                {% else %}
                Нет срока
                {% endif %}
                {% if todo.status == "N" %}
                <span class="badge bg-primary">{{ todo.get_status_display }}</span>
                {% elif todo.status == "C"%}
                <span class="badge bg-secondary">{{ todo.get_status_display }}</span>
                {% else %}
                <span class="badge bg-success">{{ todo.get_status_display }}</span>
                {% endif %}
            </div>
            <h4>Название задачи:</h4>
            <p class="fs-5">{{todo.description}}</p>
            <h4>Описание задачи:</h4>
            {% if todo.text %}
            <p class="fs-5">{{todo.text|safe}}</p>
            {% else %}
            <p class="fs-5">Описание отсутствует</p>
            {% endif %}
        </div>
        <div class=" p-2 flex-shrink-1 d-flex justify-content-between todos-item-btns">
            <div class="todos-actions-btn">
                <a href="{% url 'todo:todo_update' todo.pk %}">
                    <img src="{% static 'todo/images/icons/edit.svg' %}" alt="edit-todo" /></a>
            </div>
            <div class="todos-actions-btn">
                <a href="{% url 'todo:todo_delete' todo.pk %}">
                    <img src="{% static 'todo/images/icons/delete.svg' %}" alt="delete-todo" />
                </a>
            </div>
        </div>
    </li>
</ul>
{% endblock content %}

todo/templates/todo/todo_list.html
{% extends 'base.html' %}

{% block navigation %}
<div class="w-50 p-3 m-auto d-flex justify-content-start">
    <a class="btn btn-primary" href="{% url 'todo:todo_create' %}">Добавить новую задачу</a>
</div>
{% endblock navigation %}
{% block content %}
<ul class="list-group">
    {%if not todo_list %}
    <li class="list-group-item d-flex">
        <p class="fs-5 text-muted">Ваш список задач пуст</p>
    </li>
    {% endif %}
    {% for todo in todo_list %}
    <li class="list-group-item d-flex">
        <div class="p-2 w-100 todos-item-text">
            <div class="text-muted mb-2" style="font-size:20px;">
                {% if todo.date %}
                {{ todo.date.day }}.{{ todo.date.month }}.{{ todo.date.year }}
                {% else %}
                Нет срока
                {% endif %}
                {% if todo.status == "N" %}
                <span class="badge bg-primary">{{ todo.get_status_display }}</span>
                {% elif todo.status == "C"%}
                <span class="badge bg-secondary">{{ todo.get_status_display }}</span>
                {% else %}
                <span class="badge bg-success">{{ todo.get_status_display }}</span>
                {% endif %}
            </div>
            <p class="fs-5"><a href="{% url 'todo:todo_detail' todo.pk %}" class="link-dark">{{todo.description}}</a>
            </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock content %}

todo/templates/todo/todo_update.html
{% extends 'base.html' %}

{% block navigation %}
<div class="w-50 p-3 m-auto d-flex justify-content-start">
    <a class="btn btn-secondary" href="{% url 'todo:todo_detail' todo.pk %}">Назад</a>
</div>
{% endblock navigation %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.media}}
    <label for="description" class="form-label">Название задачи</label>
    {{form.description}}
    <label for="text" class="form-label">Описание</label>
    {{form.text}}
    <label for="status" class="form-label">Статус</label>
    {{form.status}}
    <label for="date" class="form-label">Срок выполнения(y-m-d)</label>
    <p> <input type="date" id="date" name="date" class="form-control due-date" value="{{todo.date|date:'Y-m-d'}}"></p>
    <button class="btn btn-primary mt-3" type="submit">Применить</button>
</form>
{% endblock content %}